version: '3'

services:
  db:
    container_name: back-db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root